name: Release_deploy_GolangApp_Go_Fortune

on:
  push:
    branches:
    - "v[0-9]+.[0-9]+"

jobs:
  release-and-deploy:
    runs-on:  ubuntu-latest
    if: "!contains(github.event.head_commit.message, '#NORUN')"
    steps:
    - name: Print the branch
      run: echo "current branch - ${{ github.ref_name }}"

    - name: Check branch
      uses: actions/checkout@v3
      with:
        ref:  ${{ github.ref_name }}

    - name: Node-v3
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: release branches name
      id: create-new-release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: ${{ github.ref_name }}

    - name: Railway Installation
      run: npm i -g @railway/cli

    - name: Deployment railway setup
      run: railway up
      env:
        RAILWAY_TOKEN: ${{ secrets.OSCAR_RAILWAY_TOKEN }}

    - name: Jason format send
      id: slack
      uses: slackapi/slack-github-action@v1.23.0
      with:
        payload: |
          {
            "blocks": [
              {
                "type": "header",
                "text": {
                  "type": "plain_text",
                  "text": "GDipSA55 CI/CD MinShanMon Assignment",
                  "emoji": true
                }
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "Name:\nMin Shan Mon"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "Metriculation:\nA0265086X"
                  }
                ]
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "Email:\nshanmon2017@gmail.com"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "Repository:\nhttps://github.com/MinShanMon/go-fortune"
                  }
                ]
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "Deployment:\nhttps://go-fortune-production-7cee.up.railway.app"
                  }
                ]
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "<https://https://go-fortune-production-7cee.up.railway.app/|Open Application>"
                }
              }
            ]
          }
  
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.OSCAR_SLACK_DOMAIN }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK